### ISSUE TITLE
The shape from iterator.get_next()

### ISSUE THREAD

**Issue by CangHaiQingYue** [secsilm/understaing-datasets-estimators-tfrecords#3]
Hi,
I have a question about the shape from iterator.get_next().
I convert an image to TFRecord, when I get the image through iterator.get_next(), I find that the shape of the image is [1, (an big number)]. 
And I find that in your file 'save-and-read-cifar10-tfrecords.ipynb' has the same question. 
Is that ok to train the network or need other operation?

![pic](https://user-images.githubusercontent.com/30284428/39871285-e62bbb4e-5496-11e8-9d62-d9bee65b5140.png)

**Comment by secsilm** [comment]
@CangHaiQingYue This is not a problem. You need to flatten the 3-dimensional image to a 1-dimensional image before feeding into a neural network, i.e. if the images' dimension is `[32, 32, 3]`, then the flat image is `[1, 3072]` (32×32×3).

**Comment by CangHaiQingYue** [comment]
I'm not very clear that in CNN there is any operation which flatt the image with 3-D to 1-D.
And before convert to TfRecord the size of all images( 4 images) is [321,481,3], but after read from TFRecord I get 4 images shape with different size, as shown in the figure. And any of them cannot reshape to [321,481,3].
![123](https://user-images.githubusercontent.com/30284428/39911366-b70cbdf8-552d-11e8-8455-ffbedae5424e.png)

**Comment by secsilm** [comment]
Sorry for my unclear explaination. I think it's convenient for storing data in tfrecords to convert 3-D image to 1-D image. Acually you can also not do this. Then you don't need the following code any more:

```python
x = tf.reshape(features, [-1, 32, 32, 3])
```

For you reshaping problem, you can check your flat images shape before writing them to tfrecords to see if it's right.

**Comment by CangHaiQingYue** [comment]
Thank I will check again
